= The structures of subatomic particles

_The whole universe may be pictured as one big electromagnetic field._

It did _not_ begin with a “Big Bang,” and it is _not_ expanding. It is
in stasis and is visible only out to about 13.8 billion light years.
This is because there is no “vacuum,” but instead the electromagnetic
field. Light must travel through this field and thus degrades. The
degraded light forms the Cosmic Microwave Background.

Within the universal electromagnetic field, there are these structures
we know as “electrons,” “protons,” and “neutrons.” They are dynamic
entities full of swirling electromagnetism. Nevertheless, some of the
key components of these structures may be visualized as shown in this
directory’s plots.

Notice there are no “quarks” and there is no “strong force.” The three
inseparable electromagnetic toroids of the proton and neutron were
mistaken for “quarks.”

The subatomic “anti-particles” are similar to the usual ones, but have
some dynamic properties reversed. This reversal makes them unstable in
the geometric-and-time structure of the universe.
