= The structures of subatomic particles

_The whole universe may be pictured as one big electromagnetic field._

It did _not_ begin with a “Big Bang,” and it is _not_ expanding. It is
in stasis and is visible only out to about 13.8 billion light years.
This is because there is no “vacuum,” but instead the electromagnetic
field. Light must travel through this field and thus degrades. The
degraded light forms the Cosmic Microwave
Background.footnote:[Honestly, how physicists get away with ignoring
that all of outer space must be an electrogravitomagnetic field is
beyond me. That gravity itself is an electromagnetic effect proves
mostly that Special Relativity was wrong and James Clerk Maxwell was
right. Maxwell mistakenly believed in a luminiferous ether, but
Special Relativity merely _implicitly_ assumes that _the ether exists
but is a universally fixed solid_. Einstein never could have found the
Unified Field Theory, because he had no bullshit detector, but
Maxwell’s main impediment to finding it was he did not have
_Cl(4,1,1)_ and the need to explain Michelson-Morley.]

Within the universal electromagnetic field, there are these structures
we know as “electrons,” “protons,” and “neutrons.” They are dynamic
entities full of swirling electromagnetism. Nevertheless, some of the
key components of these structures may be visualized as shown in this
directory’s plots.

Notice there are no “quarks” and there is no “strong force.” The three
inseparable electromagnetic toroids of the proton and neutron were
mistaken for “quarks.”

The subatomic “anti-particles” are similar to the usual ones, but have
some dynamic properties reversed. This reversal makes them unstable in
the geometry-and-time structure of the universe.
